// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlock = `-- name: CreateBlock :one
INSERT INTO blocks (blocker_id, blocked_id)
VALUES ($1, $2)
RETURNING id, blocker_id, blocked_id, created_at
`

type CreateBlockParams struct {
	BlockerID int32
	BlockedID int32
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error) {
	row := q.db.QueryRow(ctx, createBlock, arg.BlockerID, arg.BlockedID)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.BlockerID,
		&i.BlockedID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks
WHERE blocker_id = $1 AND blocked_id = $2
`

type DeleteBlockParams struct {
	BlockerID int32
	BlockedID int32
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.Exec(ctx, deleteBlock, arg.BlockerID, arg.BlockedID)
	return err
}

const getBlock = `-- name: GetBlock :one
SELECT id, blocker_id, blocked_id, created_at
FROM blocks
WHERE blocker_id = $1 AND blocked_id = $2
`

type GetBlockParams struct {
	BlockerID int32
	BlockedID int32
}

func (q *Queries) GetBlock(ctx context.Context, arg GetBlockParams) (Block, error) {
	row := q.db.QueryRow(ctx, getBlock, arg.BlockerID, arg.BlockedID)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.BlockerID,
		&i.BlockedID,
		&i.CreatedAt,
	)
	return i, err
}

const listBlockedUsers = `-- name: ListBlockedUsers :many
SELECT
    b.id,
    b.blocker_id,
    b.blocked_id,
    b.created_at,
    u.username,
    u.avatar_url,
    u.avatar_color
FROM blocks b
JOIN users u ON u.id = b.blocked_id
WHERE b.blocker_id = $1
ORDER BY b.created_at DESC
`

type ListBlockedUsersRow struct {
	ID          int32
	BlockerID   int32
	BlockedID   int32
	CreatedAt   pgtype.Timestamptz
	Username    string
	AvatarUrl   pgtype.Text
	AvatarColor pgtype.Text
}

func (q *Queries) ListBlockedUsers(ctx context.Context, blockerID int32) ([]ListBlockedUsersRow, error) {
	rows, err := q.db.Query(ctx, listBlockedUsers, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockedUsersRow
	for rows.Next() {
		var i ListBlockedUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.BlockerID,
			&i.BlockedID,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
			&i.AvatarColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
