// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dm_conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDmConversationParticipant = `-- name: AddDmConversationParticipant :one
INSERT INTO dm_conversation_participants (conversation_id, user_id)
VALUES ($1, $2)
RETURNING conversation_id, user_id, joined_at
`

type AddDmConversationParticipantParams struct {
	ConversationID int32
	UserID         int32
}

func (q *Queries) AddDmConversationParticipant(ctx context.Context, arg AddDmConversationParticipantParams) (DmConversationParticipant, error) {
	row := q.db.QueryRow(ctx, addDmConversationParticipant, arg.ConversationID, arg.UserID)
	var i DmConversationParticipant
	err := row.Scan(&i.ConversationID, &i.UserID, &i.JoinedAt)
	return i, err
}

const createDmConversation = `-- name: CreateDmConversation :one
INSERT INTO dm_conversations DEFAULT VALUES
RETURNING id, created_at
`

func (q *Queries) CreateDmConversation(ctx context.Context) (DmConversation, error) {
	row := q.db.QueryRow(ctx, createDmConversation)
	var i DmConversation
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getDmConversationByUserPair = `-- name: GetDmConversationByUserPair :one
SELECT
    c.id,
    c.created_at
FROM dm_conversations c
JOIN dm_conversation_participants p1 ON p1.conversation_id = c.id
JOIN dm_conversation_participants p2 ON p2.conversation_id = c.id
WHERE p1.user_id = $1
  AND p2.user_id = $2
LIMIT 1
`

type GetDmConversationByUserPairParams struct {
	UserID   int32
	UserID_2 int32
}

func (q *Queries) GetDmConversationByUserPair(ctx context.Context, arg GetDmConversationByUserPairParams) (DmConversation, error) {
	row := q.db.QueryRow(ctx, getDmConversationByUserPair, arg.UserID, arg.UserID_2)
	var i DmConversation
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getDmConversationVisibility = `-- name: GetDmConversationVisibility :one
SELECT conversation_id, user_id, hidden_at
FROM dm_conversation_visibility
WHERE conversation_id = $1 AND user_id = $2
`

type GetDmConversationVisibilityParams struct {
	ConversationID int32
	UserID         int32
}

func (q *Queries) GetDmConversationVisibility(ctx context.Context, arg GetDmConversationVisibilityParams) (DmConversationVisibility, error) {
	row := q.db.QueryRow(ctx, getDmConversationVisibility, arg.ConversationID, arg.UserID)
	var i DmConversationVisibility
	err := row.Scan(&i.ConversationID, &i.UserID, &i.HiddenAt)
	return i, err
}

const hideDmConversationForUser = `-- name: HideDmConversationForUser :one
INSERT INTO dm_conversation_visibility (conversation_id, user_id, hidden_at)
VALUES ($1, $2, CURRENT_TIMESTAMP)
ON CONFLICT (conversation_id, user_id)
DO UPDATE SET hidden_at = EXCLUDED.hidden_at
RETURNING conversation_id, user_id, hidden_at
`

type HideDmConversationForUserParams struct {
	ConversationID int32
	UserID         int32
}

func (q *Queries) HideDmConversationForUser(ctx context.Context, arg HideDmConversationForUserParams) (DmConversationVisibility, error) {
	row := q.db.QueryRow(ctx, hideDmConversationForUser, arg.ConversationID, arg.UserID)
	var i DmConversationVisibility
	err := row.Scan(&i.ConversationID, &i.UserID, &i.HiddenAt)
	return i, err
}

const listVisibleDmConversationsForUser = `-- name: ListVisibleDmConversationsForUser :many
SELECT
    c.id,
    c.created_at,
    other_user.id AS other_user_id,
    other_user.username AS other_username,
    other_user.avatar_url AS other_avatar_url,
    other_user.avatar_color AS other_avatar_color,
    COALESCE(last_message.content, '') AS last_message_content,
    last_message.created_at AS last_message_created_at
FROM dm_conversations c
JOIN dm_conversation_participants self_participant
    ON self_participant.conversation_id = c.id
JOIN dm_conversation_participants other_participant
    ON other_participant.conversation_id = c.id
   AND other_participant.user_id <> self_participant.user_id
JOIN users other_user ON other_user.id = other_participant.user_id
LEFT JOIN dm_conversation_visibility visibility
    ON visibility.conversation_id = c.id
   AND visibility.user_id = self_participant.user_id
LEFT JOIN LATERAL (
    SELECT content, created_at
    FROM dm_messages
    WHERE conversation_id = c.id
    ORDER BY created_at DESC
    LIMIT 1
) last_message ON TRUE
WHERE self_participant.user_id = $1
  AND visibility.hidden_at IS NULL
ORDER BY COALESCE(last_message.created_at, c.created_at) DESC
`

type ListVisibleDmConversationsForUserRow struct {
	ID                   int32
	CreatedAt            pgtype.Timestamptz
	OtherUserID          int32
	OtherUsername        string
	OtherAvatarUrl       pgtype.Text
	OtherAvatarColor     pgtype.Text
	LastMessageContent   string
	LastMessageCreatedAt pgtype.Timestamptz
}

func (q *Queries) ListVisibleDmConversationsForUser(ctx context.Context, userID int32) ([]ListVisibleDmConversationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listVisibleDmConversationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisibleDmConversationsForUserRow
	for rows.Next() {
		var i ListVisibleDmConversationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.OtherUserID,
			&i.OtherUsername,
			&i.OtherAvatarUrl,
			&i.OtherAvatarColor,
			&i.LastMessageContent,
			&i.LastMessageCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unhideDmConversationForUser = `-- name: UnhideDmConversationForUser :one
INSERT INTO dm_conversation_visibility (conversation_id, user_id, hidden_at)
VALUES ($1, $2, NULL)
ON CONFLICT (conversation_id, user_id)
DO UPDATE SET hidden_at = NULL
RETURNING conversation_id, user_id, hidden_at
`

type UnhideDmConversationForUserParams struct {
	ConversationID int32
	UserID         int32
}

func (q *Queries) UnhideDmConversationForUser(ctx context.Context, arg UnhideDmConversationForUserParams) (DmConversationVisibility, error) {
	row := q.db.QueryRow(ctx, unhideDmConversationForUser, arg.ConversationID, arg.UserID)
	var i DmConversationVisibility
	err := row.Scan(&i.ConversationID, &i.UserID, &i.HiddenAt)
	return i, err
}
