// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dm_messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDmMessage = `-- name: CreateDmMessage :one
INSERT INTO dm_messages (conversation_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, user_id, content, created_at
`

type CreateDmMessageParams struct {
	ConversationID int32
	UserID         int32
	Content        string
}

func (q *Queries) CreateDmMessage(ctx context.Context, arg CreateDmMessageParams) (DmMessage, error) {
	row := q.db.QueryRow(ctx, createDmMessage, arg.ConversationID, arg.UserID, arg.Content)
	var i DmMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listDmMessagesByConversation = `-- name: ListDmMessagesByConversation :many
SELECT
    m.id,
    m.conversation_id,
    m.user_id,
    m.content,
    m.created_at,
    u.username AS username,
    u.avatar_url AS avatar_url,
    u.avatar_color AS avatar_color
FROM dm_messages m
LEFT JOIN users u ON m.user_id = u.id
WHERE m.conversation_id = $1
ORDER BY m.created_at ASC
LIMIT $2 OFFSET $3
`

type ListDmMessagesByConversationParams struct {
	ConversationID int32
	Limit          int32
	Offset         int32
}

type ListDmMessagesByConversationRow struct {
	ID             int32
	ConversationID int32
	UserID         int32
	Content        string
	CreatedAt      pgtype.Timestamptz
	Username       pgtype.Text
	AvatarUrl      pgtype.Text
	AvatarColor    pgtype.Text
}

func (q *Queries) ListDmMessagesByConversation(ctx context.Context, arg ListDmMessagesByConversationParams) ([]ListDmMessagesByConversationRow, error) {
	rows, err := q.db.Query(ctx, listDmMessagesByConversation, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDmMessagesByConversationRow
	for rows.Next() {
		var i ListDmMessagesByConversationRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
			&i.AvatarColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
