// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friendships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO friendships (user_id, friend_id, requester_id, status)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, friend_id, requester_id, status, created_at
`

type CreateFriendshipParams struct {
	UserID      int32
	FriendID    int32
	RequesterID int32
	Status      string
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, createFriendship,
		arg.UserID,
		arg.FriendID,
		arg.RequesterID,
		arg.Status,
	)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.RequesterID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships
WHERE user_id = $1 AND friend_id = $2
`

type DeleteFriendshipParams struct {
	UserID   int32
	FriendID int32
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.Exec(ctx, deleteFriendship, arg.UserID, arg.FriendID)
	return err
}

const getFriendshipByID = `-- name: GetFriendshipByID :one
SELECT id, user_id, friend_id, requester_id, status, created_at
FROM friendships
WHERE id = $1
`

func (q *Queries) GetFriendshipByID(ctx context.Context, id int32) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendshipByID, id)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.RequesterID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getFriendshipByUsers = `-- name: GetFriendshipByUsers :one
SELECT id, user_id, friend_id, requester_id, status, created_at
FROM friendships
WHERE user_id = $1 AND friend_id = $2
`

type GetFriendshipByUsersParams struct {
	UserID   int32
	FriendID int32
}

func (q *Queries) GetFriendshipByUsers(ctx context.Context, arg GetFriendshipByUsersParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendshipByUsers, arg.UserID, arg.FriendID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.RequesterID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAcceptedFriends = `-- name: ListAcceptedFriends :many
SELECT
    u.id,
    u.username,
    u.avatar_url,
    u.avatar_color,
    f.created_at AS friended_at
FROM friendships f
JOIN users u
    ON u.id = CASE
        WHEN f.user_id = $1 THEN f.friend_id
        ELSE f.user_id
    END
WHERE (f.user_id = $1 OR f.friend_id = $1)
  AND f.status = 'accepted'
ORDER BY f.created_at ASC
`

type ListAcceptedFriendsRow struct {
	ID          int32
	Username    string
	AvatarUrl   pgtype.Text
	AvatarColor pgtype.Text
	FriendedAt  pgtype.Timestamptz
}

func (q *Queries) ListAcceptedFriends(ctx context.Context, userID int32) ([]ListAcceptedFriendsRow, error) {
	rows, err := q.db.Query(ctx, listAcceptedFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAcceptedFriendsRow
	for rows.Next() {
		var i ListAcceptedFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarUrl,
			&i.AvatarColor,
			&i.FriendedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingFriendRequests = `-- name: ListIncomingFriendRequests :many
SELECT
    f.id,
    f.user_id,
    f.friend_id,
    f.requester_id,
    f.status,
    f.created_at,
    u.username,
    u.avatar_url,
    u.avatar_color
FROM friendships f
JOIN users u ON u.id = f.user_id
WHERE f.friend_id = $1
  AND f.status = 'pending'
ORDER BY f.created_at ASC
`

type ListIncomingFriendRequestsRow struct {
	ID          int32
	UserID      int32
	FriendID    int32
	RequesterID int32
	Status      string
	CreatedAt   pgtype.Timestamptz
	Username    string
	AvatarUrl   pgtype.Text
	AvatarColor pgtype.Text
}

func (q *Queries) ListIncomingFriendRequests(ctx context.Context, friendID int32) ([]ListIncomingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listIncomingFriendRequests, friendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncomingFriendRequestsRow
	for rows.Next() {
		var i ListIncomingFriendRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FriendID,
			&i.RequesterID,
			&i.Status,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
			&i.AvatarColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingFriendRequests = `-- name: ListOutgoingFriendRequests :many
SELECT
    f.id,
    f.user_id,
    f.friend_id,
    f.requester_id,
    f.status,
    f.created_at,
    u.username,
    u.avatar_url,
    u.avatar_color
FROM friendships f
JOIN users u ON u.id = f.friend_id
WHERE f.user_id = $1
  AND f.status = 'pending'
ORDER BY f.created_at ASC
`

type ListOutgoingFriendRequestsRow struct {
	ID          int32
	UserID      int32
	FriendID    int32
	RequesterID int32
	Status      string
	CreatedAt   pgtype.Timestamptz
	Username    string
	AvatarUrl   pgtype.Text
	AvatarColor pgtype.Text
}

func (q *Queries) ListOutgoingFriendRequests(ctx context.Context, userID int32) ([]ListOutgoingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listOutgoingFriendRequests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutgoingFriendRequestsRow
	for rows.Next() {
		var i ListOutgoingFriendRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FriendID,
			&i.RequesterID,
			&i.Status,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
			&i.AvatarColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFriendshipStatus = `-- name: UpdateFriendshipStatus :one
UPDATE friendships
SET status = $3
WHERE user_id = $1 AND friend_id = $2
RETURNING id, user_id, friend_id, requester_id, status, created_at
`

type UpdateFriendshipStatusParams struct {
	UserID   int32
	FriendID int32
	Status   string
}

func (q *Queries) UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, updateFriendshipStatus, arg.UserID, arg.FriendID, arg.Status)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.RequesterID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
