// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	ID        int32
	BlockerID int32
	BlockedID int32
	CreatedAt pgtype.Timestamptz
}

type Channel struct {
	ID        int32
	Name      string
	CreatedBy pgtype.Int4
	CreatedAt pgtype.Timestamptz
	ServerID  int32
}

type DmConversation struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
}

type DmConversationParticipant struct {
	ConversationID int32
	UserID         int32
	JoinedAt       pgtype.Timestamptz
}

type DmConversationVisibility struct {
	ConversationID int32
	UserID         int32
	HiddenAt       pgtype.Timestamptz
}

type DmMessage struct {
	ID             int32
	ConversationID int32
	UserID         int32
	Content        string
	CreatedAt      pgtype.Timestamptz
}

type Friendship struct {
	ID          int32
	UserID      int32
	FriendID    int32
	RequesterID int32
	Status      string
	CreatedAt   pgtype.Timestamptz
}

type Message struct {
	ID        int32
	ChannelID int32
	UserID    int32
	Content   string
	CreatedAt pgtype.Timestamptz
}

type Server struct {
	ID        int32
	Name      string
	CreatorID pgtype.Int4
	IsPublic  pgtype.Bool
	CreatedAt pgtype.Timestamp
}

type ServerMember struct {
	ServerID int32
	UserID   int32
	JoinedAt pgtype.Timestamp
}

type User struct {
	ID          int32
	Username    string
	Password    string
	CreatedAt   pgtype.Timestamptz
	AvatarUrl   pgtype.Text
	AvatarColor pgtype.Text
}
